version: "3.9"

services:
  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=property_price
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=password