version: "3.9"

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
#  db:
#    image: postgres:15
#    ports:
#      - "5432:5432"
#    environment:
#      - POSTGRES_DB=property_price
#      - POSTGRES_USER=db_user
#      - POSTGRES_PASSWORD=password
#  property-price-cosmos-db:
#    build:
#      context: .
#      dockerfile: ./property-price-cosmos-db/Dockerfile
#    image: property-price-cosmos-db
#    container_name: property-price-cosmos-db
#    ports:
#      - "8080:8080"