name: Build and Deploy to Cloud Run

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: open-source-apps-001
  IMAGE: property-price-api
  REGISTRY_HOSTNAME: gcr.io
  CLOUD_RUN_SERVICE: property-price-api

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: open-source-apps-001
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
      - name: Authenticate with Container Registry
        run: |
          gcloud --quiet auth configure-docker
      # Build the Docker image
      - name: Build
        run: |-
          cd property-price-api
          docker build -t \
          "$REGISTRY_HOSTNAME/$PROJECT_ID/$IMAGE:$GITHUB_SHA" -t \
          "$REGISTRY_HOSTNAME/$PROJECT_ID/$IMAGE:latest" .
          cd ..
      # Push the Docker image to Google Container Registry
      - name: Push
        run: |
          cd property-price-api
          docker push "$REGISTRY_HOSTNAME/$PROJECT_ID/$IMAGE:$GITHUB_SHA" 
          docker push "$REGISTRY_HOSTNAME"/$PROJECT_ID/"$IMAGE":latest
          cd ..
      - name: Deploy
        run: |
          cd property-price-api
          gcloud run deploy ${CLOUD_RUN_SERVICE} --image "$REGISTRY_HOSTNAME/$PROJECT_ID/$IMAGE:$GITHUB_SHA" --region europe-west1 \
          --update-secrets=MONGO_DB_CONNECTION_STRING=property-price-api-mongo-db-connection-string:latest\
          ,JWT_SECRET=jwt-secret:latest
          cd ..
