name: Build and Deploy to Cloud Run

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: open-source-apps-001
  API_IMAGE: property-price-api
  INGEST_IMAGE: property-price-ingest
  REGISTRY_HOSTNAME: gcr.io
  CLOUD_RUN_SERVICE: property-price-api
  INGEST_CLOUD_RUN_SERVICE: property-price-ingest
  COSMOS_DB_CLOUD_RUN_SERVICE: property-price-cosmos-db

jobs:
  build-pack:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ["8.0.x"]
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build
      - name: Pack the NuGet package
        run: dotnet pack -c Release
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ["7.0.x"]
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build
      - name: Test
        run: dotnet test
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: open-source-apps-001
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
      - name: Authenticate with Container Registry
        run: |
          gcloud --quiet auth configure-docker
      # Build the API Docker image
      - name: Build API
        run: |-
          cd property-price-api
          docker build -t \
          "$REGISTRY_HOSTNAME/$PROJECT_ID/$API_IMAGE:$GITHUB_SHA" -t \
          "$REGISTRY_HOSTNAME/$PROJECT_ID/$API_IMAGE:latest" .
          cd ..
      # Push the Docker image to Google Container Registry
      - name: Push
        run: |
          cd property-price-api
          docker push "$REGISTRY_HOSTNAME/$PROJECT_ID/$API_IMAGE:$GITHUB_SHA" 
          docker push "$REGISTRY_HOSTNAME"/$PROJECT_ID/"$API_IMAGE":latest
          cd ..
      # Build the ingest engine Docker image
      - name: Build ingest engine
        run: |-
          docker build -f property-price-ingest/Dockerfile -t \
          "$REGISTRY_HOSTNAME/$PROJECT_ID/$INGEST_IMAGE:$GITHUB_SHA" -t \
          "$REGISTRY_HOSTNAME/$PROJECT_ID/$INGEST_IMAGE:latest" .
      # Push the ingest engine Docker image to Google Container Registry
      - name: Push
        run: |
          docker push "$REGISTRY_HOSTNAME/$PROJECT_ID/$INGEST_IMAGE:$GITHUB_SHA" 
          docker push "$REGISTRY_HOSTNAME"/$PROJECT_ID/"$INGEST_IMAGE":latest
      # Build the Cosmos DB service Docker image
      - name: Build Cosmos DB service
        run: |-
          docker build -f property-price-cosmos-db/Dockerfile -t \
          "$REGISTRY_HOSTNAME/$PROJECT_ID/$COSMOS_DB_CLOUD_RUN_SERVICE:$GITHUB_SHA" -t \
          "$REGISTRY_HOSTNAME/$PROJECT_ID/$COSMOS_DB_CLOUD_RUN_SERVICE:latest" .
      # Push the Cosmos DB service Docker image to Google Container Registry
      - name: Push
        run: |
          docker push "$REGISTRY_HOSTNAME/$PROJECT_ID/$COSMOS_DB_CLOUD_RUN_SERVICE:$GITHUB_SHA" 
          docker push "$REGISTRY_HOSTNAME"/$PROJECT_ID/"$COSMOS_DB_CLOUD_RUN_SERVICE":latest
      - name: Deploy
        run: |
          gcloud run deploy ${CLOUD_RUN_SERVICE} --image "$REGISTRY_HOSTNAME/$PROJECT_ID/$API_IMAGE:$GITHUB_SHA" --region europe-west1 \
          --update-secrets=MONGO_DB_CONNECTION_STRING=property-price-api-mongo-db-connection-string:latest\
          ,JWT_SECRET=jwt-secret:latest
          gcloud run deploy ${INGEST_CLOUD_RUN_SERVICE} --image "$REGISTRY_HOSTNAME/$PROJECT_ID/$INGEST_IMAGE:$GITHUB_SHA" --region europe-west1 \
          --update-secrets=MONGO_DB_CONNECTION_STRING=property-price-api-mongo-db-connection-string:latest
          gcloud run deploy ${COSMOS_DB_CLOUD_RUN_SERVICE} --image "$REGISTRY_HOSTNAME/$PROJECT_ID/$COSMOS_DB_CLOUD_RUN_SERVICE:$GITHUB_SHA" --region europe-west1
